### ISSUE TITLE
Problem when doing a initremote

### ISSUE THREAD

**Issue by InAnimaTe** [Schnouki/git-annex-remote-hubic#7]
After doing a `git init` and then a `git annex init`, I try to add the remote and the following transpires:

```
┌[mloria@aquarius] [master ⚡] 
└[~/testannex]> git annex initremote my-hubic-remote type=external externaltype=hubic encryption=shared hubic_container=annex hubic_path=/ embedcreds=no
initremote my-hubic-remote (encryption setup) (shared cipher) Traceback (most recent call last):
  File "/usr/bin/git-annex-remote-hubic", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3143, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3129, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3156, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 649, in _build_master
    ws = cls()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 642, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 698, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2136, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2518, in from_location
    version = cls._version_from_metadata(dist_path) or version
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2841, in _version_from_metadata
    return _version_from_file(strm)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2483, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 116: ordinal not in range(128)
git-annex: external special remote protocol error, unexpectedly received "" (unable to parse command)
```

Some details:

```
┌[mloria@aquarius] [master ⚡] 
└[~/testannex]> python --version
Python 3.5.0
```

```
┌[mloria@aquarius] [master ⚡] [1]
└[~/testannex]> git-annex version
git-annex version: 5.20151116-gbe86081
build flags: Assistant Webapp Webapp-secure Pairing Testsuite S3 WebDAV Inotify DBus DesktopNotify XMPP ConcurrentOutput DNS Feeds Quvi TDFA TorrentParser Database
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt S3 bup directory rsync web bittorrent webdav tahoe glacier ddar hook external
local repository version: 5
supported repository version: 5
upgrade supported from repository versions: 0 1 2 4
```

Also, is there something extra I should be doing to make it show up in the "remote types" list above?

**Comment by InAnimaTe** [comment]
Let me also stress that I am fairly new to git-annex. This could totally be me derping around ;)

btw, I'm using Arch Linux and [this](https://aur.archlinux.org/packages/git-annex-bin/) AUR package.

**Comment by InAnimaTe** [comment]
So i tried this again and it works just fine. closing.
